# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5bc07f2ffc218a50abd7434f6be56087c16417bb9de52dd33b7a54e368824b1c2130e685f3845f78005ddb11cb2c498fb50d46cea24d1556ad18217901e37d3

test:
  secret_key_base: 88bbce93694af4e1756265fd3f7d279630474e492c09d2b352666dbd33acb98003a580c55b6d349393201a42b209dd2825948a49b6ceee790e63a5652129ed05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
